CLS

Loser:

PRINT "Hi! My name is Bob Smith and I'll be your host for tonight so just"
PRINT "sit back, relax, and enjoy the show.  First of all I would like to"
PRINT "extend a big thank you to Poopi Co. Foods for sponsoring this show"
PRINT "and for providing the entire staff with a life supply of Poopicola"
PRINT
PRINT "As you sit in your large cushioned leather seat and stare absently"
PRINT "at the television, you think to yourself that you have experienced"
PRINT "this same sensation before.  Then you remember that you have done"
PRINT "this very activity for the last four weeks, at least ever since you"
PRINT "lost your job as a janitor at the Poopicola factory here in Helena,"
PRINT "Montana.  For once in your life you are sick of being a nobody, and"
PRINT "now you suddenly feel like you want to be someone and do something"
PRINT "with your pitiful excuse for a human existance."
PRINT
PRINT "1 Go hunt for a supper-bad-dude job and get started with life."
PRINT "2 Look for some adrenalin pumping sport to take up."
PRINT "3 Sit and do nothing just like you've done for most of your life."
PRINT
INPUT "", A$
IF A$ = "1" THEN GOTO Jobs
IF A$ = "2" THEN GOTO Sports
IF A$ = "3" THEN GOTO Sit

Jobs:

CLS
PRINT "You grab the classified adds off of the shelf and tear through"
PRINT "the pages.  Now you are filled with vigor and you have a burning"
PRINT "desire jump around in joy and excitement, but you think better"
PRINT "of it and continue your search.  An hour of so later, you have"
PRINT "come up with four jobs which do not require any skill or prior"
PRINT "training.  It seems that there is a dandy little job over at"
Sports:
Sit:




