CLS
BEGIN:
COLOR 9
LOCATE 10, 10
PRINT "               I HATE YOU!"
SLEEP 2
CLS
LOCATE 10, 10
PRINT "               YOU HATE ME!"
SLEEP 2
CLS
LOCATE 10, 10
PRINT "               BARNEY'S JUST NOT GOOD FOR ME!"
SLEEP 2
CLS
LOCATE 10, 10
PRINT "               I THINK I'M GOING TO POUND HIM IN THE FACE!"
SLEEP 2
LOCATE 10, 10
CLS
LOCATE 10, 10
PRINT "               AND DELETE HIM FROM THE HUMAN RACE!"
SLEEP 2
CLS
GOTO WANT
END

WANT:
CLS
INPUT "What do you rate that song with 1 bieng good and 10 bad: ", W$

IF W$ = "1" THEN PRINT "Hey, you liked it a lot didn't ya! Alright, maybe ya can join the biz."

IF W$ = "2" THEN PRINT "I guess ya think it wasn't perfect, eh? Well, it was perfect me matey!"

IF W$ = "3" THEN PRINT "Well, you probably think it's good but not stupendous. Well, it is!"

IF W$ = "4" THEN PRINT "Why, you barely think it's above average! Well, I know it a #1!"

IF W$ = "5" THEN PRINT "Why, that's exactly average! ADVICE: Lower you number 5 points up!"

IF W$ = "6" THEN PRINT "No way! That's not even average! Why you're just unappreciative!"


IF W$ = "7" THEN PRINT "I don't think so! Why you little snob, do it yerself!"


IF W$ = "8" THEN PRINT "That's bad to the bone! Why,just play something else if you'lll be that way!"


IF W$ = "9" THEN PRINT "Why, I'm so ashamed of you I'm not even gonna say anything it's so bad!"

IF W$ = "10" THEN PRINT "DO IT YERSELF YA STUPID SNOBBY THINK YOU CAN DO IT BETTER DUMBO! TRY!"



       


